# Generated by Django 6.0 on 2025-12-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на проекты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('author', 'Автор'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
    ]
