# Generated by Django 6.0 on 2025-12-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_project_link_profile_role_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='project_links',
            field=models.TextField(blank=True, help_text='JSON массив ссылок', null=True, verbose_name='Ссылки на проекты'),
        ),
    ]
