# Generated by Django 6.0 on 2025-12-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_project_link_profile_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_file',
            field=models.ImageField(blank=True, help_text='Загрузите аватар с вашего компьютера', null=True, upload_to='profiles/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL аватара (сохраняется автоматически после загрузки)', null=True, verbose_name='Ссылка на аватар'),
        ),
    ]
