# Generated by Django 6.0 on 2025-12-24 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('section', models.CharField(choices=[('design', 'Дизайн'), ('music', 'Музыка'), ('writing', 'Писательство'), ('video', 'Видео'), ('photography', 'Фотография'), ('programming', 'Программирование'), ('art', 'Искусство'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Раздел')),
                ('tags', models.CharField(blank=True, help_text='Выберите один или несколько тегов', max_length=500, verbose_name='Теги')),
                ('image_file', models.ImageField(blank=True, help_text='Загрузите изображение проекта (не обязательно)', null=True, upload_to='projects/images/', verbose_name='Изображение проекта')),
                ('image_url', models.URLField(blank=True, help_text='URL изображения (сохраняется автоматически после загрузки)', null=True, verbose_name='Ссылка на изображение проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
